### ISSUE TITLE
请问这个怎么用？请指点。

### ISSUE THREAD

**Issue by guojunlu** [zhujintao/dingAdsync#1]
请问这个怎么用？请指点。

**Comment by zhujintao** [comment]
> 请问这个怎么用？请指点。
下载这个https://github.com/zhujintao/dingAdsync/releases/download/0.1/dingAdsync
在linux上运行，
配置文件dingAdsync.conf 跟程序放在一样

[dingding]        # <-- 这个下面的信息为钉钉企业管理后台相关的信息 (https://oa.dingtalk.com)
corpId="xxxx"
corpSecret="xxxx"
noteappid="123456"   # <-- 这个是用来发通知的，同步时新账号会生成随机密码通知给用户

[domain]  # <- 这个下面的信息是 windows Ad 域相关的信息

domain="DRIXMT.LOCAL"      
server="srv01-w12r2"  # <-- ad域控服务地址
mainou="K-Think"        # <-- 自定义的ou 同步进来的账号归属这个ou
account="administrator@drixmt.local"  # <-- ad域控账号
password="j@1985v.com"  # <-- ad域控账号密码
ldapssl=true  #  <--- 如果ad域的 ldap服务配置了ssl证书，值为true 才可以为生成随机密码。否则只会同步账号信息，账号为disable状态
